### ISSUE TITLE
How to implement?

### ISSUE THREAD

**Issue by axsddlr** [RedfishGroup/firebase_worker_queue#5]
any example js file to show how to implement this library into a project?

**Comment by m0ose** [comment]
We do need a good sample program. At the very least it would help testing.

**Comment by axsddlr** [comment]
@m0ose would be a great help, i was looking to use this in a nodejs project i am doing via firebase but did not understand how to initially implement it. thanks for the reply

**Comment by m0ose** [comment]
Here is a webpage demo. It should be fairly straight forward to use the worker queue portion in Node. 
https://redfishgroup.github.io/firebase_worker_queue/demo/pi.html
https://github.com/RedfishGroup/firebase_worker_queue/blob/master/demo/pi.html

**Comment by stigmergic** [comment]
Thanks @m0ose nice demo!
